OBJS += riscv/cpu.o                                                   \
        riscv/tx_double_init.o                                        \

RVV-OBJS += riscv/tx_double_riscv.o                                   \
